config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users, path: :gurus,
             path_names: { sign_in: :login, sign_out: :logout },
             controllers: { sessions: 'users/sessions' }

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: %i[show update] do
    get :result, on: :member
    post :gist, on: :member
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: :index
    resources :badges
  end
  resources :feedbacks, only: %i[new create]
  resources :user_badges, only: :index
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :user_badges, dependent: :destroy
  has_many :users, through: :user_badges

  validates :title, :rule, :image, presence: true

  BADGE_RULES = {
      'Прохождение всех тестов из категории' => :rule_all_in_category,
      'Прохождение теста с первой попытки' => :rule_first_try,
      'Прохождение всех тестов уровня' => :rule_all_by_level
  }.freeze

  def self.images
    badges = Dir.glob("app/assets/images/badges/*")
    
    # делаем путь относительным, чтобы иконка попала в assets pipeline
    badges.map { |b| b.delete_prefix('app/assets/images/') }
  end

end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController
  before_action :set_badge, only: %i[show edit update destroy]

  def index
    @badges = Badge.all
  end

  def new
    @badge = Badge.new
  end

  def create
    @badge = Badge.new(badge_params)

    if @badge.save
      redirect_to admin_badge_url(@badge)
    else
      render :new
    end
  end

  def update
    if @badge.update(badge_params)
      redirect_to admin_badge_url(@badge)
    else
      render :edit
    end
  end

  def destroy
    @badge.destroy
    redirect_to admin_badges_url
  end

  private

  def set_badge
    @badge = Badge.find(params[:id])
  end

  def badge_params
    params.require(:badge).permit(:title, :image, :rule)
  end
end

app/views/admin/badges/_form.html.erb
<%= form_with model: [:admin, @badge], local: true, class: 'mb-5' do |f| %>
  <%= render 'shared/errors', resource: @badge %>
  <div class="field">
    <div><%= f.label :title %></div>
    <div><%= f.text_field :title %></div>
  </div>
  <div class="field">
    <div><%= f.label :image %></div>
    <div><%= f.select :image, options_for_select(Badge.images), prompt: true %></div>
  </div>
  <div class="field">
    <div><%= f.label :rule %></div>
    <div><%= f.select :rule, options_for_select(Badge::BADGE_RULES) %></div>
  </div>
  <div class="field">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/badges/edit.html.erb
<div class="container">
  <h1><%= t('.header')%></h1>

  <%= render 'form', badge: @badge %>
  <%= link_to t('.show'), admin_badge_url(@badge), class: 'btn btn-primary' %>
  <%= link_to t('.back'), admin_badges_url, class: 'btn btn-primary' %>
</div>

app/views/admin/badges/index.html.erb
<div class="container mb-5">
  <h1><%= t('.header')%></h1>
  <table class="table">
    <thead>
      <th>Название</th>
      <th>Иконка</th>
      <th>Правило</th>
      <th colspan="3">Действия</th>
    </thead>
    <tbody>
    <% @badges.each do |badge| %>
      <tr>
        <td><%= badge.title %></td>
        <td><%= image_tag(badge.image, size: 60) %></td>
        <td><%= badge.rule %></td>
        <td>
          <%= link_to t('.show'), admin_badge_url(badge) %>
          <%= link_to t('.edit'), edit_admin_badge_url(badge) %>
          <%= link_to t('.delete'), admin_badge_url(badge),
                          method: :delete, data: { confirm: 'Уверены?' }%></td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <%= link_to t('.new_badge'), new_admin_badge_path, class: "btn btn-primary" %>
</div>

app/views/admin/badges/new.html.erb
<div class="container">
  <h1><%= t('.header')%></h1>
  <%= render 'form', badge: @badge %>
  <%= link_to t('.back'), admin_badges_path, class: 'btn btn-primary' %>
</div>

app/views/admin/badges/show.html.erb
<div class="container">
  <h1><%= t('.title')%>: <%= @badge.title %></h1>

  <p><%= image_tag(@badge.image, size: 60) %></p>

  <h2><%= t('.users')%></h2>
  <ul>
    <% @badge.users.distinct.each do |user|%>
      <li><%= user.email %> (<%= @badge.users.count%> бэйджа)</li>
    <% end %>
  </ul>
  
  <h2><%= t('.rule')%></h2>
  <p><%= @badge.rule %></p>

  <div>
    <%= link_to t('.edit'), edit_admin_badge_path(@badge), class: 'btn btn-primary' %>
    <%= link_to t('.back'), admin_badges_path, class: 'btn btn-primary' %>
  </div>
</div>