config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users, path: :gurus,
             path_names: { sign_in: :login, sign_out: :logout },
             controllers: { sessions: 'users/sessions' }

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: %i[show update] do
    get :result, on: :member
    post :gist, on: :member
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: :index
    resources :badges
  end
  resources :feedbacks, only: %i[new create]
  resources :user_badges, only: :index
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :test
  belongs_to :user
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_next_question

  SUCCESS_THRESHOLD = 85

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)
    self.passed = true if success?
    save!
  end

  def completed?
    current_question.nil?
  end

  def current_question_number
    test.questions.where('id <= ?', current_question.id).count
  end

  def questions_count
    test.questions.count
  end

  def percent_result
    correct_questions * 100 / questions_count
  end

  def success?
    percent_result >= SUCCESS_THRESHOLD
  end

  def passage_progress
    100 / questions_count * (current_question_number - 1)
  end

  def time_is_over?
    time_left.negative?
  end

  def time_left
    test.test_time_to_sec - (Time.current - created_at)
  end

  private

  def before_validation_set_next_question
    self.current_question = if new_record?
      test.questions.order(:id).first if test.present?
    else
      test.questions.order(:id).where('id > ?', current_question.id).first
    end
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end
end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController
  before_action :authenticate_user!
  before_action :test_passage, only: %i[show update result gist]

  def update
    @test_passage.accept!(params[:answer_ids])

    if @test_passage.completed? || @test_passage.time_is_over?
      TestsMailer.completed_test(@test_passage).deliver_now
      if @test_passage.success?
        badge = BadgesService.new(@test_passage)
        badge.call
        flash.now[:notice] = "Получен новый бэйдж"
      end
      redirect_to result_test_passage_path(@test_passage)
    else
      render :show
    end
  end

  def result; end

  def gist
    gist_service = GistQuestionService.new(@test_passage.current_question)
    result = gist_service.call
    if gist_service.success?
      url = result[:html_url]
      save_gist(url)
      flash[:success] = t('.success', gist_url: view_context.link_to(url, url, target: '_blank'))
    else
      flash[:alert] = t('.failure')
    end
    redirect_to @test_passage
  end

  def save_gist(url)
    Gist.create!(
      gist_url: url,
      question: @test_passage.current_question,
      user: current_user
      )
  rescue => e
    logger.error "Gist not saved: #{e.message}"
  end

  private

  def test_passage
    @test_passage = TestPassage.find(params[:id])
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
  TEST_PASSAGE = {
    success: 'Тест пройден',
    failure: 'Тест не пройден'
  }.freeze

  def result_message(test_passage)
    test_passage.success? ? TEST_PASSAGE[:success] : TEST_PASSAGE[:failure]
  end

  def success_class(test_passage)
    test_passage.success? ? 'success' : 'fail'
  end

  def question_number(test_passage)
    "Вопрос #{test_passage.current_question_number}/#{test_passage.questions_count}"
  end
end

app/views/test_passages/result.html.erb
<div class="container">
  <h1><%= t('.header', title: @test_passage.test.title) %></h1>

  <div>
    <p>Ваш результат:</p>
    <p class="test__result test__result--<%= success_class(@test_passage) %>">
      <%= @test_passage.percent_result %> % <%= result_message(@test_passage) %>
    </p>
  </div>

  <div>
    <p>
      <%= link_to 'К списку тестов', tests_path %>
    </p>
  </div>
</div>

app/views/test_passages/show.html.erb
<div class="container">
  <h1>Текущий тест: <%= @test_passage.test.title %></h1>

  <% if @test_passage.test.test_time.present? %>
    <%= content_tag :div, class: 'js-timer', data:{time_left: @test_passage.time_left} do %>
      <div class='time js-time'></div>
    <%end%>
  <% end %>
  
  <p>
    <%= question_number(@test_passage) %>
  </p>

  <%= content_tag :div, class: 'progress js-test-passage-progress', data: { value: @test_passage.passage_progress } do %>
    <div class="progress-bar progress-bar-striped bg-success" role="progressbar">
      <%= @test_passage.passage_progress %> %
    </div>
  <% end %>

  <div>
    <p>
      <%= @test_passage.current_question.body %>
    </p>
  </div>

  <%= form_with url: test_passage_path(@test_passage), local: true, method: :put do |form| %>
    <div class="field">
      <%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :body, include_hidden: false do |b| %>
        <div>
          <%= b.check_box id: "answer_ids_#{b.object.id}" %>
          <%= b.label %>
        </div>
      <% end %>
    </div>
    <div class="field">
      <%= link_to t('.add_gist'), gist_test_passage_path(@test_passage), method: :post %>
    </div>
    <div class="field">
      <%= form.submit 'Следующий вопрос' %>
    </div>
  <% end %>
</div>