config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users, path: :gurus,
             path_names: { sign_in: :login, sign_out: :logout },
             controllers: { sessions: 'users/sessions' }

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: %i[show update] do
    get :result, on: :member
    post :gist, on: :member
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: :index
    resources :badges
  end
  resources :feedbacks, only: %i[new create]
  resources :user_badges, only: :index
end

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.any? %>
  <%= content_tag :div, class: 'js-resource-errors', data: { resource_id: resource.try(:id) } do %>
    <h2><%= t('.header', count: resource.errors.count) %>:</h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/shared/_flash.html.erb
<div class="container mb-5">
  <% flash.each do |key, value| %>
    <%= content_tag :div, value.html_safe, class: "alert alert-#{key}", role: "alert" %>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div>&copy; <%= current_year %></div>
    <div>Автор: mrkmx</div>
    <div>Ссылка на репозиторий: <%= github_url "mrkmx", "test-guru" %></div>
    <div>
      <a href="https://thinknetica.com/" target="_blank" rel="noopener noreferrer">
        Учебный проект в онлайн-школе Thinknetica
      </a>
    </div>
    <div><%= link_to t('feedbacks.link'), new_feedback_path %></div>
  </div>
</footer>

app/views/shared/_header.html.erb
<% if user_signed_in? %>
  <div class="container mb-4">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to 'TestGuru', root_path, class: "navbar-brand" %>
      <% if current_user.admin? %>
        <small> 
          <%= link_to 'Перейти в панель управления', admin_tests_path, class: "text-muted" %>
        </small>
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarNavAltMarkup">
        <strong class="navbar-text">
          <%= current_user.first_name || current_user.email %>
        </strong>
        <div class="navbar-nav">
          <% if current_user.admin? %>
            <%= link_to 'Админка', admin_tests_path, class: "nav-item nav-link" %>
          <% end %>
          <%= link_to 'Тесты', tests_path, class: "nav-item nav-link" %>
          <%= link_to 'Бэйджи', user_badges_path, class: "nav-item nav-link" %>
          <%= link_to 'Выйти', destroy_user_session_path, method: :delete, class: "nav-item nav-link" %>
        </div>
      </div>
    </nav>
  </div>
<% end %>