config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users, path: :gurus,
             path_names: { sign_in: :login, sign_out: :logout },
             controllers: { sessions: 'users/sessions' }

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: %i[show update] do
    get :result, on: :member
    post :gist, on: :member
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: :index
    resources :badges
  end
  resources :feedbacks, only: %i[new create]
  resources :user_badges, only: :index
end

app/views/admin/shared/_header.html.erb
<div class="container mb-4">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to 'TestGuru | Панель управления', admin_tests_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNavAltMarkup">
      <strong class="navbar-text">
        <%= current_user.first_name || current_user.email %>
      </strong>
      <div class="navbar-nav">
        <%= link_to 'Gists', admin_gists_path, class: "nav-item nav-link" %>
        <%= link_to 'Админка', admin_tests_path, class: "nav-item nav-link" %>
        <%= link_to 'Тесты', tests_path, class: "nav-item nav-link" %>
        <%= link_to 'Бэйджи', admin_badges_path, class: "nav-item nav-link" %>
        <%= link_to 'Выйти', destroy_user_session_path, method: :delete, class: "nav-item nav-link" %>
      </div>
    </div>
  </nav>
</div>